name = "go-proxy-bingai"
main = "worker.js"
compatibility_date = "2024-04-29"
workers_dev = true
rules = [
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true }
]

[placement]
mode = "smart"

# wrangler.toml (wrangler v3.78.6^)
[observability]
enabled = true
